import { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import CodeMirror from "@/components/CodeMirror";
import { isValidJSON } from "@/utils";

import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState({});

  const handleOnChangeEditor = (value) => {
    const { isValid } = isValidJSON(value.target.value);

    if (value.length === 0) {
      localStorage.setItem('data', {});
      setValue({});
    }

    if (isValid) {
      localStorage.setItem('data', value.target.value);
      setValue(JSON.parse(value.target.value));
    }
  };

  useEffect(() => {
    if (typeof window !== "undefined") {
      const data = localStorage.getItem('data');
      console.log(data)
      if (!data) {
        setValue({});
        return;
      }
      setValue(JSON.parse(data));
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>CodeMirror example</h1>
        <div className={styles.editor}>
          <CodeMirror
            value={JSON.stringify(value, null, 2)}
            onChange={(event) => handleOnChangeEditor(event)}
          />
        </div>
      </main>
    </>
  );
}
